# Generated by Django 5.1.2 on 2025-09-07 11:05

import django.db.models.deletion
import parametres.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STOCK', '0008_mouvementstock_reference'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_promotion', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe'), ('prix_specifique', 'Prix spécifique'), ('acheter_x_obtenir_y', 'Acheter X obtenir Y gratuit'), ('lot', 'Lot (X pour le prix de Y)')], max_length=20, verbose_name='Type de promotion')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planifiee', 'Planifiée'), ('expiree', 'Expirée')], default='planifiee', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
            bases=(parametres.mixins.EntrepriseAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromotionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_secondaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur secondaire')),
                ('quantite_min', models.PositiveIntegerField(default=1, verbose_name='Quantité minimum')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STOCK.produit', verbose_name='Produit')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Ligne de promotion',
                'verbose_name_plural': 'Lignes de promotion',
                'unique_together': {('promotion', 'produit')},
            },
        ),
    ]
