# Generated by Django 5.1.2 on 2025-09-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date_mouvement'], 'verbose_name': 'Mouvement de Stock', 'verbose_name_plural': 'Mouvements de Stock'},
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='prix_unitaire_moment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire au moment du mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('inventaire', 'Inventaire'), ('ajustement', 'Ajustement')], max_length=20),
        ),
    ]
