# Generated by Django 5.1.2 on 2025-09-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0002_alter_mouvementstock_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvementstock',
            old_name='prix_unitaire_moment',
            new_name='prix_achat',
        ),
    ]
