# Generated by Django 5.1.2 on 2025-09-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0003_rename_prix_unitaire_moment_mouvementstock_prix_achat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvementstock',
            old_name='prix_achat',
            new_name='prix_unitaire_moment',
        ),
    ]
