# Generated by Django 5.1.2 on 2025-09-04 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0004_rename_prix_achat_mouvementstock_prix_unitaire_moment'),
        ('comptabilite', '0005_ecriturecomptable_mouvement_stock_lie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventairephysique',
            options={'ordering': ['-date'], 'verbose_name': 'Inventaire Physique', 'verbose_name_plural': 'Inventaires Physiques'},
        ),
        migrations.AddField(
            model_name='inventairephysique',
            name='ecriture_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecriturecomptable'),
        ),
        migrations.AddField(
            model_name='inventairephysique',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('comptabilise', 'Comptabilisé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='inventairephysique',
            name='valeur_ecart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
