# Generated by Django 5.1.2 on 2025-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0005_alter_inventairephysique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
