# Generated by Django 5.1.2 on 2025-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0006_alter_produit_code_barre_alter_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.ImageField(blank=True, null=True, upload_to='media/barcodes/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/produits/'),
        ),
    ]
