# Generated by Django 5.1.2 on 2025-09-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0007_alter_produit_code_barre_alter_produit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence (BL, Facture, etc.)'),
        ),
    ]
