# Generated by Django 5.1.2 on 2025-09-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0009_alter_notification_destinataire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseConnaissance',
        ),
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatbotKnowledge',
        ),
        migrations.DeleteModel(
            name='ChatbotConversation',
        ),
    ]
