# Generated by Django 5.1.2 on 2025-09-03 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0002_ligneecriture_entreprise'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(max_length=20, verbose_name='Code postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/photos/', verbose_name='Photo')),
                ('cv', models.FileField(blank=True, null=True, upload_to='employes/cv/', verbose_name='CV')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('compte_comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.plancomptableohada', verbose_name='Compte comptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='grh.employe', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'unique_together': {('entreprise', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('FREELANCE', 'Freelance')], max_length=20, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire de base')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('RESILIE', 'Résilié')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('duree_essai', models.IntegerField(blank=True, null=True, verbose_name="Durée d'essai (jours)")),
                ('date_fin_essai', models.DateField(blank=True, null=True, verbose_name="Date de fin de période d'essai")),
                ('heures_semaine', models.IntegerField(default=35, verbose_name='Heures par semaine')),
                ('jours_conges_an', models.IntegerField(default=25, verbose_name='Jours de congés par an')),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/', verbose_name='Fichier du contrat')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé maternité'), ('PATERNITE', 'Congé paternité'), ('SANS_SOLDE', 'Congé sans solde'), ('EXCEPTIONNEL', 'Congé exceptionnel')], max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_jours', models.IntegerField(verbose_name='Nombre de jours')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demandé'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='DEMANDE', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.employe', verbose_name='Employé')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides', to='grh.employe', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=7, verbose_name='Période (YYYY-MM)')),
                ('date_edition', models.DateField(auto_now_add=True, verbose_name="Date d'édition")),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire brut')),
                ('total_cotisations', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total cotisations')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire net')),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net à payer')),
                ('jours_travailles', models.IntegerField(verbose_name='Jours travaillés')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Heures travaillées')),
                ('fichier_bulletin', models.FileField(blank=True, null=True, upload_to='bulletins/', verbose_name='Fichier bulletin')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.contrat', verbose_name='Contrat')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'unique_together': {('employe', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='LigneBulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('GAINS', 'Gains'), ('RETENUES', 'Retenues')], max_length=10, verbose_name='Type de ligne')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='grh.bulletinpaie', verbose_name='Bulletin')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin de paie',
                'verbose_name_plural': 'Lignes de bulletin de paie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('intitule', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('FREELANCE', 'Freelance')], default='CDI', max_length=20, verbose_name='Type de contrat')),
                ('salaire_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire minimum')),
                ('salaire_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire maximum')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.departement', verbose_name='Département')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'unique_together': {('entreprise', 'code')},
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.poste', verbose_name='Poste'),
        ),
    ]
