# Generated by Django 5.1.2 on 2025-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='carte_employe',
            field=models.ImageField(blank=True, null=True, upload_to='cartes_employes/', verbose_name="Carte d'employé"),
        ),
    ]
