# Generated by Django 5.1.2 on 2025-09-03 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0002_employe_carte_employe'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures travaillées')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('CONGE', 'Congé'), ('MALADIE', 'Maladie'), ('AUTRE', 'Autre')], default='PRESENT', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grh.employe', verbose_name='Employé')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
