# Generated by Django 5.1.2 on 2025-07-10 00:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STOCK', '0001_initial'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, verbose_name='Numéro de Commande')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('recue', 'Reçue'), ('partiellement_livree', 'Partiellement livrée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', max_length=50, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_commandes', to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Commande d'Achat",
                'verbose_name_plural': "Commandes d'Achat",
                'ordering': ['-date_commande', '-created_at'],
                'permissions': [('valider_commandeachat', "Peut valider une commande d'achat"), ('annuler_commandeachat', "Peut annuler une commande d'achat"), ('exporter_commandeachat', "Peut exporter les commandes d'achat")],
            },
        ),
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=50, unique=True)),
                ('date_reception', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_reception_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achats.commandeachat')),
            ],
            options={
                'verbose_name': 'Bon de réception',
                'verbose_name_plural': 'Bons de réception',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_fournisseurs', to='parametres.entreprise')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='achats.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='LigneCommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire HT')),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de TVA à appliquer à cette ligne (en pourcentage).', max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva_ligne', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Montant de la TVA calculé pour cette ligne.', max_digits=10, verbose_name='Montant TVA')),
                ('livree', models.BooleanField(default=False, verbose_name='Livrée')),
                ('quantite_livree', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantité Livrée')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandeachat', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne de Commande d'Achat",
                'verbose_name_plural': "Lignes de Commandes d'Achat",
            },
        ),
        migrations.CreateModel(
            name='LigneBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditionnement', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.bonreception')),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reception', to='achats.lignecommandeachat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fournisseur',
            constraint=models.UniqueConstraint(fields=('entreprise', 'code'), name='unique_code_fournisseur_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='commandeachat',
            constraint=models.UniqueConstraint(fields=('entreprise', 'numero_commande'), name='unique_commande_achat_par_entreprise'),
        ),
        migrations.AlterUniqueTogether(
            name='lignecommandeachat',
            unique_together={('commande', 'produit')},
        ),
    ]
