# Generated by Django 5.1.2 on 2025-09-07 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_facturefournisseur'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='achats.facturefournisseur')),
            ],
            options={
                'verbose_name': 'Paiement Fournisseur',
                'verbose_name_plural': 'Paiements Fournisseurs',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
    ]
