# Generated by Django 5.1.2 on 2025-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_paiementfournisseur'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='categorie',
            field=models.CharField(choices=[('matieres_premieres', 'Fournisseur de matières premières'), ('equipements', "Fournisseur d'équipements"), ('services', 'Fournisseur de services'), ('divers', 'Divers')], default='divers', max_length=50),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_premier_contact',
            field=models.DateField(blank=True, null=True, verbose_name='Date du premier contact'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='nom_banque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='nom_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du contact'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations supplémentaires sur le fournisseur'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='numero_siret',
            field=models.CharField(blank=True, max_length=14, verbose_name='Numéro SIRET'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='numero_tva',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro TVA intracommunautaire'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='telephone_secondaire',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='fournisseur',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_siret', ''), _negated=True), fields=('entreprise', 'numero_siret'), name='unique_siret_fournisseur_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='fournisseur',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_tva', ''), _negated=True), fields=('entreprise', 'numero_tva'), name='unique_tva_fournisseur_entreprise'),
        ),
    ]
