# Generated by Django 5.1.2 on 2025-09-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_alter_fournisseur_options_fournisseur_bic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveConstraint(
            model_name='fournisseur',
            name='unique_siret_fournisseur_entreprise',
        ),
        migrations.RemoveConstraint(
            model_name='fournisseur',
            name='unique_tva_fournisseur_entreprise',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='date_premier_contact',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='nom_banque',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='nom_contact',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='numero_siret',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='numero_tva',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='site_web',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='telephone_secondaire',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='ville',
        ),
    ]
