# Generated by Django 5.1.2 on 2025-09-07 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_alter_fournisseur_options_and_more'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonreception',
            name='numero_bon',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='bonreception',
            constraint=models.UniqueConstraint(fields=('entreprise', 'numero_bon'), name='unique_numero_bon_par_entreprise'),
        ),
    ]
