# Generated by Django 5.1.2 on 2025-09-11 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_alter_bonreception_numero_bon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonreception',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lignebonreception',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignebonreception',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
