# Generated by Django 5.1.2 on 2025-09-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0007_bonreception_montant_ht_bonreception_montant_ttc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonreception',
            old_name='montant_ht',
            new_name='total_ht',
        ),
        migrations.RenameField(
            model_name='bonreception',
            old_name='montant_ttc',
            new_name='total_ttc',
        ),
        migrations.RenameField(
            model_name='bonreception',
            old_name='montant_tva',
            new_name='total_tva',
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='bon_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='achats.bonreception'),
        ),
    ]
