# Generated by Django 5.1.2 on 2025-09-11 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0008_rename_montant_ht_bonreception_total_ht_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignebonreception',
            options={'verbose_name': 'Ligne de bon de réception', 'verbose_name_plural': 'Lignes de bons de réception'},
        ),
        migrations.AddField(
            model_name='lignebonreception',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignebonreception',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
