# Generated by Django 5.1.2 on 2025-09-11 18:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0009_alter_lignebonreception_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='taux_tva_defaut',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taux de TVA par défaut pour ce fournisseur (en pourcentage)', max_digits=5, verbose_name='Taux TVA par défaut (%)'),
        ),
    ]
