# Generated by Django 5.1.2 on 2025-09-11 18:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0009_alter_notification_destinataire'),
        ('achats', '0010_fournisseur_taux_tva_defaut'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeachat',
            options={'ordering': ['-date_commande', '-created_at'], 'verbose_name': "Commande d'Achat", 'verbose_name_plural': "Commandes d'Achat"},
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_commandes', to='parametres.entreprise'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='achats.fournisseur'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandeachat'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='montant_tva_ligne',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
