# Generated by Django 5.1.2 on 2025-09-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0011_alter_commandeachat_options_and_more'),
        ('parametres', '0020_alter_entreprise_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturefournisseur',
            name='numero_facture',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='facturefournisseur',
            unique_together={('entreprise', 'numero_facture')},
        ),
    ]
