# Generated by Django 5.1.2 on 2025-07-10 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STOCK', '0001_initial'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('en_cours', 'En cours de préparation'), ('livre_partiel', 'Livré partiellement'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STOCK.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('prepare', 'Préparé'), ('livre', 'Livré'), ('retour', 'Retour')], default='prepare', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('echeance', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('facture', 'Facturé')], default='brouillon', max_length=20)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STOCK.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.devis'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('echeance', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye_partiel', 'Payé partiellement'), ('paye', 'Payé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.bonlivraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STOCK.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.commande')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.devis')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit')),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.bonlivraison')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.devis')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.facture')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('fonds_ouverture', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fonds_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=20)),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.pointdevente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentePOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STOCK.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='ventes.sessionpos')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.sessionpos')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.ventepos')),
            ],
        ),
        migrations.CreateModel(
            name='LigneVentePOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.ventepos')),
            ],
        ),
    ]
