# Generated by Django 5.1.2 on 2025-07-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignedevis',
            old_name='article',
            new_name='produit',
        ),
    ]
