# Generated by Django 5.1.2 on 2025-07-11 01:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_rename_article_lignedevis_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignecommande',
            old_name='article',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
