# Generated by Django 5.1.2 on 2025-07-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_alter_devis_numero_devisstatuthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devisstatuthistory',
            options={'ordering': ['-change_date'], 'verbose_name': 'Historique du Statut du Devis', 'verbose_name_plural': 'Historiques des Statuts des Devis'},
        ),
        migrations.RenameField(
            model_name='devisstatuthistory',
            old_name='changed_at',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='devisstatuthistory',
            old_name='ancien_statut',
            new_name='new_status',
        ),
        migrations.RenameField(
            model_name='devisstatuthistory',
            old_name='commentaire',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='devisstatuthistory',
            name='nouveau_statut',
        ),
        migrations.AddField(
            model_name='devisstatuthistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('facture', 'Facturé')], max_length=20, null=True),
        ),
    ]
