# Generated by Django 5.1.2 on 2025-07-11 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_alter_devisstatuthistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devisstatuthistory',
            options={'ordering': ['-changed_date'], 'verbose_name': 'Historique de statut de devis', 'verbose_name_plural': 'Historiques de statut de devis'},
        ),
        migrations.RemoveField(
            model_name='devisstatuthistory',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='devisstatuthistory',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='devisstatuthistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='devisstatuthistory',
            name='old_status',
        ),
        migrations.AddField(
            model_name='devisstatuthistory',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('facture', 'Facturé')], max_length=20, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AddField(
            model_name='devisstatuthistory',
            name='changed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de modification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devisstatuthistory',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='devisstatuthistory',
            name='nouveau_statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('facture', 'Facturé')], default=20, max_length=20, verbose_name='Nouveau statut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devisstatuthistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
