# Generated by Django 5.1.2 on 2025-07-11 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_alter_devisstatuthistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devisstatuthistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Historique Statut Devis', 'verbose_name_plural': 'Historiques Statuts Devis'},
        ),
        migrations.RemoveField(
            model_name='devisstatuthistory',
            name='changed_date',
        ),
        migrations.AddField(
            model_name='devisstatuthistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devisstatuthistory',
            name='ancien_statut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devisstatuthistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devisstatuthistory',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devisstatuthistory',
            name='nouveau_statut',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='DevisAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('envoi_email', 'Envoi Email'), ('changement_statut', 'Changement de Statut'), ('impression_pdf', 'Impression PDF')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ventes.devis')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit Devis",
                'verbose_name_plural': "Journaux d'Audit Devis",
                'ordering': ['-performed_at'],
            },
        ),
    ]
