# Generated by Django 5.1.2 on 2025-07-11 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_alter_devisstatuthistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_paiement', 'En attente de paiement'), ('confirme', 'Confirmée'), ('en_preparation', 'En préparation'), ('expedie', 'Expédiée'), ('livre', 'Livrée'), ('annule', 'Annulée'), ('rembourse', 'Remboursée')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='CommandeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('changement_statut', 'Changement de Statut'), ('paiement_enregistre', 'Paiement Enregistré'), ('conversion_devis', 'Conversion depuis Devis')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ventes.commande')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit Commande",
                'verbose_name_plural': "Journaux d'Audit Commande",
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandeStatutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.commande')),
            ],
            options={
                'verbose_name': 'Historique Statut Commande',
                'verbose_name_plural': 'Historiques Statuts Commande',
                'ordering': ['-changed_at'],
            },
        ),
    ]
