# Generated by Django 5.1.2 on 2025-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_commande_total_ht_commande_total_ttc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeauditlog',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('changement_statut', 'Changement de Statut'), ('paiement_enregistre', 'Paiement Enregistré'), ('conversion_devis', 'Conversion depuis Devis'), ('alert_fraude', 'Alerte Fraude')], max_length=50),
        ),
    ]
