# Generated by Django 5.1.2 on 2025-07-12 20:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0009_alter_commandeauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignebonlivraison',
            old_name='article',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='ventes.commande'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='statut',
            field=models.CharField(choices=[('prepare', 'Préparé'), ('livre', 'Livré'), ('retour', 'Retour'), ('annule', 'Annulé')], default='prepare', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignebonlivraison',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignebonlivraison',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='BonLivraisonAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('changement_statut', 'Changement de Statut'), ('impression_pdf', 'Impression PDF'), ('envoi_email', 'Envoi Email'), ('generation_auto', 'Génération Automatique')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('bon_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ventes.bonlivraison')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonlivraison_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit Bon de Livraison",
                'verbose_name_plural': "Journaux d'Audit Bon de Livraison",
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='BonLivraisonStatutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.bonlivraison')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Statut Bon de Livraison',
                'verbose_name_plural': 'Historiques Statuts Bon de Livraison',
                'ordering': ['-changed_at'],
            },
        ),
    ]
