# Generated by Django 5.1.2 on 2025-07-13 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0001_initial'),
        ('ventes', '0010_rename_article_lignebonlivraison_produit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('exporter_facture', 'Peut exporter les factures'), ('envoyer_facture', 'Peut envoyer les factures par email')], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['id'], 'verbose_name': 'Ligne de Facture', 'verbose_name_plural': 'Lignes de Facture'},
        ),
        migrations.AddField(
            model_name='facture',
            name='conditions_paiement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='devise',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='facture',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='STOCK.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('mobile', 'Paiement mobile'), ('crypto', 'Cryptomonnaie'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='FactureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('changement_statut', 'Changement de Statut'), ('envoi_email', 'Envoi Email'), ('impression_pdf', 'Impression PDF'), ('paiement_enregistre', 'Paiement Enregistré')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ventes.facture')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit Facture",
                'verbose_name_plural': "Journaux d'Audit Facture",
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='FactureStatutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.facture')),
            ],
            options={
                'verbose_name': 'Historique Statut Facture',
                'verbose_name_plural': 'Historiques Statuts Facture',
                'ordering': ['-changed_at'],
            },
        ),
    ]
