# Generated by Django 5.1.2 on 2025-08-19 12:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0011_alter_facture_options_alter_lignefacture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'accepte'), ('refuse', 'Refusé'), ('facture', 'Facturé')], default='brouillon', max_length=20),
        ),
    ]
