# Generated by Django 5.1.2 on 2025-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_bonlivraison_total_ht_bonlivraison_total_ttc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligneventepos',
            old_name='article',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('prepare', 'Préparé'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], default='prepare', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('Confirmee', 'Confirmée'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
    ]
