# Generated by Django 5.1.2 on 2025-08-20 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0013_rename_article_ligneventepos_produit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcartCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('excedent', 'Excédent'), ('manquant', 'Manquant'), ('regularisation', 'Regularisation')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecarts_caisse', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecarts_crees', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecarts_caisse', to='ventes.sessionpos')),
            ],
            options={
                'verbose_name': 'Écart de caisse',
                'verbose_name_plural': 'Écarts de caisse',
                'ordering': ['-date_creation'],
            },
        ),
    ]
