# Generated by Django 5.1.2 on 2025-08-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0014_ecartcaisse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignefacture',
            old_name='article',
            new_name='produit',
        ),
    ]
