# Generated by Django 5.1.2 on 2025-08-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        ('ventes', '0015_rename_article_lignefacture_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointdevente',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='caissiers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'entreprise': models.F('entreprise'), 'role': 'CAISSIER'}, related_name='pos_caissiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='bon_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='ventes.bonlivraison'),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='adresse',
            field=models.TextField(blank=True, default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'entreprise': models.F('entreprise'), 'role': 'CAISSIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pointdevente',
            unique_together={('entreprise', 'code')},
        ),
    ]
