# Generated by Django 5.1.2 on 2025-08-27 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0016_alter_pointdevente_options_pointdevente_caissiers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdevente',
            name='caissiers',
            field=models.ManyToManyField(blank=True, related_name='pos_caissiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
