# Generated by Django 5.1.2 on 2025-09-02 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0017_alter_pointdevente_caissiers_alter_pointdevente_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('paye_partiel', 'Payé partiellement'), ('paye', 'Payé'), ('annulee', 'Annulée')], default='brouillon', max_length=20),
        ),
    ]
