# Generated by Django 5.1.2 on 2025-09-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0018_facture_date_validation_facture_validated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_facture', '-created_at'], 'permissions': [('exporter_facture', 'Peut exporter les factures'), ('envoyer_facture', 'Peut envoyer les factures par email')], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='echeance',
            new_name='date_echeance',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='date',
            new_name='date_facture',
        ),
    ]
