# Generated by Django 5.1.2 on 2025-09-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0019_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneventepos',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ligneventepos',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
