# Generated by Django 5.1.2 on 2025-09-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        ('ventes', '0020_alter_ligneventepos_montant_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='bonlivraison',
            unique_together={('entreprise', 'numero')},
        ),
    ]
