# Generated by Django 5.1.2 on 2025-09-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        ('ventes', '0021_alter_bonlivraison_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('entreprise', 'numero')},
        ),
    ]
