# Generated by Django 5.1.2 on 2025-09-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0020_alter_entreprise_logo'),
        ('ventes', '0022_alter_facture_numero_alter_facture_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventepos',
            name='entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventes_pos', to='parametres.entreprise', verbose_name='Entreprise'),
            preserve_default=False,
        ),
    ]
