# Generated by Django 5.1.2 on 2025-09-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0023_ventepos_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventepos',
            name='entreprise',
        ),
    ]
