# Generated by Django 5.1.2 on 2025-09-23 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandedemo',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Demande de démonstration', 'verbose_name_plural': 'Demandes de démonstration'},
        ),
        migrations.AlterField(
            model_name='demandedemo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='demandedemo',
            name='entreprise',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='demandedemo',
            name='message',
            field=models.TextField(blank=True, help_text='Décrivez vos besoins spécifiques', verbose_name='Message additionnel'),
        ),
        migrations.AlterField(
            model_name='demandedemo',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='demandedemo',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
