# Generated by Django 5.1.2 on 2025-05-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_historiqueabonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='taux_par_defaut',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='Taux par défaut'),
        ),
    ]
