# Generated by Django 5.1.2 on 2025-05-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_devise_taux_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='taux_par_defaut',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='taux_par_defaut'),
        ),
    ]
