# Generated by Django 5.1.2 on 2025-05-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_alter_devise_taux_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement_courant', to='parametres.entreprise', verbose_name='Entreprise associée'),
        ),
    ]
