# Generated by Django 5.1.2 on 2025-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_alter_abonnement_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé'),
        ),
    ]
