# Generated by Django 5.1.2 on 2025-05-27 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_abonnement_est_actif_abonnement_montant_paye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.AddField(
            model_name='abonnement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abonnement',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_historique', to='parametres.entreprise', verbose_name='Entreprise associée'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='id_abonnement_paiement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID abonnement fournisseur'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('BANK', 'Virement bancaire')], max_length=10, null=True, verbose_name='Méthode de paiement'),
        ),
    ]
