# Generated by Django 5.1.2 on 2025-05-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_alter_abonnement_options_abonnement_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='parametres.entreprise', verbose_name='Entreprise associée'),
        ),
    ]
