# Generated by Django 5.1.2 on 2025-05-27 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_alter_abonnement_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date de début effective de l'abonnement", verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Laissez vide pour un abonnement illimité', null=True, verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='parametres.entreprise', verbose_name='Entreprise associée'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='est_actif',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='id_abonnement_paiement',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID abonnement fournisseur'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('BANK', 'Virement bancaire'), ('CASH', 'Espèces')], max_length=10, null=True, verbose_name='Méthode de paiement'),
        ),
        migrations.AddIndex(
            model_name='abonnement',
            index=models.Index(fields=['entreprise', 'est_actif'], name='parametres__entrepr_9d41ad_idx'),
        ),
        migrations.AddIndex(
            model_name='abonnement',
            index=models.Index(fields=['date_fin'], name='parametres__date_fi_eae472_idx'),
        ),
    ]
