# Generated by Django 5.1.2 on 2025-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_alter_abonnement_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantarification',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
