# Generated by Django 5.1.2 on 2025-06-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_plantarification_est_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique identifiant le module', max_length=20, unique=True, verbose_name='Code du module')),
                ('nom', models.CharField(help_text='Nom complet du module', max_length=100, verbose_name='Nom du module')),
                ('categorie', models.CharField(choices=[('STOCK', 'Gestion de stock'), ('VENTE', 'Vente'), ('COMPTA', 'Comptabilité'), ('RH', 'Ressources humaines'), ('CRM', 'CRM'), ('REPORT', 'Reporting'), ('CONFIG', 'Paramétrage')], help_text='Catégorie fonctionnelle du module', max_length=10, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, help_text='Description détaillée des fonctionnalités du module', verbose_name='Description')),
                ('icone', models.CharField(default='settings', help_text="Nom de l'icône Material Icons ou Font Awesome", max_length=50, verbose_name='Icône')),
                ('actif_par_defaut', models.BooleanField(default=False, help_text='Si le module est activé par défaut pour les nouveaux abonnements', verbose_name='Actif par défaut')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans l'interface", verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.RemoveField(
            model_name='plantarification',
            name='modules_inclus',
        ),
        migrations.AddField(
            model_name='plantarification',
            name='modules_optionnels',
            field=models.ManyToManyField(blank=True, help_text='Modules disponibles en option pour ce plan', related_name='plans_optionnels', to='parametres.module', verbose_name='Modules optionnels'),
        ),
        migrations.CreateModel(
            name='DependanceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=True, help_text="Si la dépendance est obligatoire pour l'activation du module principal", verbose_name='Obligatoire')),
                ('module_dependance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependances_secondaires', to='parametres.module', verbose_name='Module dépendance')),
                ('module_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependances_principales', to='parametres.module', verbose_name='Module principal')),
            ],
            options={
                'verbose_name': 'Dépendance de module',
                'verbose_name_plural': 'Dépendances de modules',
                'unique_together': {('module_principal', 'module_dependance')},
            },
        ),
        migrations.CreateModel(
            name='ModuleEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si le module est activé pour cette entreprise', verbose_name='Est actif')),
                ('date_activation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('date_desactivation', models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_entreprise', to='parametres.entreprise', verbose_name='Entreprise')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises_modules', to='parametres.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module entreprise',
                'verbose_name_plural': 'Modules entreprise',
                'ordering': ['module__ordre_affichage'],
                'unique_together': {('entreprise', 'module')},
            },
        ),
    ]
