# Generated by Django 5.1.2 on 2025-06-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0011_module_remove_plantarification_modules_inclus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantarification',
            name='modules_inclus',
            field=models.ManyToManyField(blank=True, help_text='Modules automatiquement inclus dans ce plan', related_name='plans_inclus', to='parametres.module', verbose_name='Modules inclus'),
        ),
    ]
