# Generated by Django 5.1.2 on 2025-06-08 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0012_plantarification_modules_inclus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='taux_par_defaut',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux par défaut'),
        ),
    ]
