# Generated by Django 5.1.2 on 2025-06-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0013_alter_devise_taux_par_defaut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationsaas',
            name='modules_actifs',
        ),
    ]
