# Generated by Django 5.1.2 on 2025-06-09 12:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0015_alter_devise_taux_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='taux_par_defaut',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux par défaut (par rapport à la devise principale du SAAS)'),
        ),
    ]
