# Generated by Django 5.1.2 on 2025-06-09 21:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0016_alter_devise_taux_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsaas',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taux de TVA par défaut en pourcentage (e.g., 16.00 pour 16%)', max_digits=5),
        ),
    ]
