# Generated by Django 5.1.2 on 2025-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0017_configurationsaas_taux_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='donnees_paiement',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données de paiement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='frais_transaction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de transaction'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='id_session_paiement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de session de paiement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='net_percu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant net perçu'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='statut_paiement',
            field=models.CharField(choices=[('REQUIS', 'Paiement requis'), ('EN_ATTENTE', 'Paiement en attente'), ('COMPLETE', 'Paiement complété'), ('ECHEC', 'Paiement échoué'), ('REMBOURSE', 'Remboursé')], default='REQUIS', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
