# Generated by Django 5.1.2 on 2025-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0018_abonnement_donnees_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='taux_tva_defaut',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de TVA par défaut à appliquer pour cette entreprise (en pourcentage, ex: 20.00)', max_digits=5, verbose_name='Taux de TVA par défaut (%)'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='numero_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro Fiscal'),
        ),
    ]
