# Generated by Django 5.1.2 on 2025-09-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Logo'),
        ),
    ]
