# Generated by Django 5.1.2 on 2025-09-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0020_alter_entreprise_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationsaas',
            options={},
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='taux_tva',
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='email_from_name',
            field=models.CharField(default='ERP', max_length=100, verbose_name='Nom expéditeur'),
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Serveur SMTP'),
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe SMTP'),
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email expéditeur'),
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Port SMTP'),
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Utiliser TLS'),
        ),
        migrations.AlterField(
            model_name='configurationsaas',
            name='complexite_mdp',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('fort', 'Fort')], default='moyen', max_length=10, verbose_name='Complexité du mot de passe'),
        ),
        migrations.AlterField(
            model_name='configurationsaas',
            name='devise_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.devise', verbose_name='Devise principale'),
        ),
        migrations.AlterField(
            model_name='configurationsaas',
            name='expiration_session',
            field=models.PositiveIntegerField(default=30, verbose_name='Expiration de session (min)'),
        ),
    ]
