# Generated by Django 5.1.2 on 2025-09-23 23:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0021_alter_configurationsaas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationsaas',
            options={'verbose_name': 'Configuration SAAS', 'verbose_name_plural': 'Configurations SAAS'},
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='email_from_name',
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='configurationsaas',
            name='email_use_tls',
        ),
        migrations.AddField(
            model_name='configurationsaas',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Taux de TVA par défaut en pourcentage (e.g., 16.00 pour 16%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configurationsaas',
            name='complexite_mdp',
            field=models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Fort')], default=2, verbose_name='Complexité mot de passe'),
        ),
        migrations.AlterField(
            model_name='configurationsaas',
            name='devise_principale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametres.devise', verbose_name='Devise principale'),
        ),
        migrations.AlterField(
            model_name='configurationsaas',
            name='expiration_session',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Expiration session (minutes)'),
        ),
    ]
