# Generated by Django 5.1.2 on 2025-09-11 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('type_ia', models.CharField(choices=[('prediction', 'Prédiction'), ('classification', 'Classification'), ('recommendation', 'Recommandation'), ('anomaly', "Détection d'anomalies")], max_length=20, verbose_name="Type d'IA")),
                ('modele_ia', models.CharField(max_length=200, verbose_name='Modèle IA')),
                ('parametres', models.JSONField(default=dict, verbose_name='Paramètres')),
                ('precision', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Précision')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Intégration IA',
                'verbose_name_plural': 'Intégrations IA',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('format_export', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10, verbose_name='Format')),
                ('parametres', models.JSONField(default=dict, verbose_name="Paramètres d'export")),
                ('taille_fichier', models.BigIntegerField(default=0, verbose_name='Taille du fichier (bytes)')),
                ('chemin_fichier', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Exporté par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Export de données',
                'verbose_name_plural': 'Exports de données',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('type_import', models.CharField(max_length=50, verbose_name="Type d'import")),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('resultat', models.JSONField(default=dict, verbose_name='Résultat')),
                ('erreurs', models.JSONField(default=list, verbose_name='Erreurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Import de données',
                'verbose_name_plural': 'Imports de données',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du KPI')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code KPI')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_kpi', models.CharField(choices=[('financial', 'Financier'), ('commercial', 'Commercial'), ('stock', 'Stock'), ('rh', 'Ressources Humaines'), ('custom', 'Personnalisé')], max_length=20, verbose_name='Type de KPI')),
                ('formule', models.TextField(verbose_name='Formule de calcul')),
                ('periodicite', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20, verbose_name='Périodicité')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité de mesure')),
                ('cible', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valeur cible')),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Seuil d'alerte")),
                ('module_lie', models.CharField(choices=[('ventes', 'Ventes'), ('achats', 'Achats'), ('stock', 'Stock'), ('compta', 'Comptabilité'), ('rh', 'Ressources Humaines'), ('crm', 'CRM')], max_length=50, verbose_name='Module lié')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_rapport', models.CharField(choices=[('tableau', 'Tableau'), ('graphique', 'Graphique'), ('mixte', 'Mixte')], max_length=20, verbose_name='Type de rapport')),
                ('requete_sql', models.TextField(blank=True, verbose_name='Requête SQL')),
                ('parametres', models.JSONField(default=dict, verbose_name='Paramètres')),
                ('colonnes', models.JSONField(default=list, verbose_name='Colonnes')),
                ('options_graphique', models.JSONField(default=dict, verbose_name='Options graphique')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valeur')),
                ('date_mesure', models.DateField(verbose_name='Date de mesure')),
                ('periode', models.CharField(max_length=20, verbose_name='Période')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.kpi', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Valeur KPI',
                'verbose_name_plural': 'Valeurs KPI',
                'ordering': ['-date_mesure'],
                'unique_together': {('kpi', 'date_mesure', 'entreprise')},
            },
        ),
    ]
