# Generated by Django 5.1.2 on 2025-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_utilisateurpersonnalise_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='signature',
            field=models.ImageField(blank=True, help_text="Signature numérique de l'utilisateur", null=True, upload_to='signatures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='signature_date',
            field=models.DateField(blank=True, help_text='Date de création de la signature', null=True),
        ),
    ]
