# Generated by Django 5.1.2 on 2025-05-21 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_profilutilisateur_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='signature_svg',
            field=models.TextField(blank=True, help_text='Signature au format SVG (pour les signatures dessinées)', null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='poste',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
