# Generated by Django 5.1.2 on 2025-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_profilutilisateur_signature_svg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='signature',
            field=models.ImageField(blank=True, help_text="Signature numérique de l'utilisateur (format image)", null=True, upload_to='signatures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='signature_svg',
            field=models.TextField(blank=True, help_text='Signature au format SVG (dessin)', null=True),
        ),
    ]
