# Generated by Django 5.1.2 on 2025-05-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_utilisateurpersonnalise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurpersonnalise',
            options={'permissions': [('acces_dashboard', 'Accès au tableau de bord'), ('gerer_utilisateurs', 'Peut gérer les utilisateurs'), ('voir_statistiques', 'Peut voir les statistiques'), ('gerer_stock', 'Peut gérer le stock'), ('effectuer_vente', 'Peut effectuer des ventes'), ('historique_vente', 'Peut voir historique des ventes'), ('view_client', 'Peut voir les clients'), ('add_client', 'Peut ajouter des clients'), ('change_client', 'Peut modifier des clients'), ('delete_client', 'Peut supprimer des clients'), ('view_entreprise', 'Voir les entreprises'), ('change_abonnement', 'Modifier les abonnements'), ('view_produit', 'Peut voir les produits'), ('add_produit', 'Peut ajouter des produits'), ('change_produit', 'Peut modifier des produits'), ('delete_produit', 'Peut supprimer des produits'), ('view_categorie', 'Peut voir les catégories'), ('add_categorie', 'Peut ajouter des catégories'), ('change_categorie', 'Peut modifier des catégories'), ('delete_categorie', 'Peut supprimer des catégories'), ('add_commande', 'Créer des commandes'), ('view_commande', 'Voir les commandes'), ('change_commande', 'Modifier les commandes'), ('delete_commande', 'Supprimer des commandes'), ('valider_commande', 'Valider des commandes'), ('gerer_caisse', 'Gérer la caisse'), ('export_commande', 'Exporter des commandes'), ('view_fournisseur', 'Peut voir les fournisseurs'), ('add_fournisseur', 'Peut ajouter des fournisseurs'), ('change_fournisseur', 'Peut modifier des fournisseurs'), ('delete_fournisseur', 'Peut supprimer des fournisseurs'), ('view_achat', 'Peut voir les achats'), ('add_achat', 'Peut enregistrer des achats'), ('change_achat', 'Peut modifier des achats'), ('delete_achat', 'Peut supprimer des achats'), ('view_inventaire', 'Peut voir les inventaires'), ('add_inventaire', 'Peut créer des inventaires'), ('change_inventaire', 'Peut modifier des inventaires'), ('confirm_inventaire', 'Peut confirmer des inventaires'), ('view_parametre', 'Peut voir les paramètres'), ('change_parametre', 'Peut modifier les paramètres'), ('view_rapport', 'Peut voir les rapports'), ('generate_rapport', 'Peut générer des rapports'), ('view_tresorerie', 'Peut voir la trésorerie'), ('manage_tresorerie', 'Peut gérer la trésorerie'), ('view_backup', 'Peut voir les sauvegardes'), ('create_backup', 'Peut créer des sauvegardes'), ('restore_backup', 'Peut restaurer des sauvegardes'), ('view_promotion', 'Peut voir les promotions'), ('add_promotion', 'Peut ajouter des promotions'), ('change_promotion', 'Peut modifier des promotions'), ('delete_promotion', 'Peut supprimer des promotions'), ('apply_promotion', 'Peut appliquer des promotions'), ('view_notification', 'Peut voir les notifications'), ('manage_notification', 'Peut gérer les notifications'), ('can_manage_promotions', 'Peut gérer les promotions')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
