# Generated by Django 5.1.2 on 2025-05-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_alter_devise_taux_par_defaut'),
        ('security', '0007_alter_utilisateurpersonnalise_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurpersonnalise',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='parametres.entreprise', verbose_name='Entreprise associée'),
        ),
    ]
