# Generated by Django 5.1.2 on 2025-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_utilisateurpersonnalise_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurpersonnalise',
            name='is_saas_admin',
            field=models.BooleanField(default=False, help_text='Accès complet à toutes les entreprises', verbose_name='Administrateur SaaS'),
        ),
    ]
