# Generated by Django 5.1.2 on 2025-09-09 21:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STOCK', '0008_mouvementstock_reference'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        ('ventes', '0022_alter_facture_numero_alter_facture_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCRM',
            fields=[
            ],
            options={
                'verbose_name': 'Client CRM',
                'verbose_name_plural': 'Clients CRM',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('STOCK.client',),
        ),
        migrations.CreateModel(
            name='ObjectifCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_objectif', models.CharField(choices=[('chiffre_affaires', "Chiffre d'affaires"), ('nombre_ventes', 'Nombre de ventes'), ('taux_conversion', 'Taux de conversion'), ('nouveaux_clients', 'Nouveaux clients')], max_length=20, verbose_name="Type d'objectif")),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur cible')),
                ('valeur_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur actuelle')),
                ('periodicite', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=15, verbose_name='Périodicité')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('equipe', models.ManyToManyField(blank=True, related_name='objectifs_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Objectif commercial',
                'verbose_name_plural': 'Objectifs commerciaux',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PipelineVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Pipeline de vente',
                'verbose_name_plural': 'Pipelines de vente',
            },
        ),
        migrations.CreateModel(
            name='EtapePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('probabilite_par_defaut', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probabilité par défaut (%)')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipelinevente', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Étape de pipeline',
                'verbose_name_plural': 'Étapes de pipeline',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatutOpportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('couleur', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur')),
                ('est_gagnant', models.BooleanField(default=False, verbose_name='Statut gagnant')),
                ('est_perdant', models.BooleanField(default=False, verbose_name='Statut perdant')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Statut d'opportunité",
                'verbose_name_plural': "Statuts d'opportunité",
                'ordering': ['ordre'],
                'unique_together': {('nom', 'entreprise')},
            },
        ),
        migrations.AddField(
            model_name='pipelinevente',
            name='statuts',
            field=models.ManyToManyField(through='crm.EtapePipeline', to='crm.statutopportunite', verbose_name='Statuts'),
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'opportunité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant estimé')),
                ('probabilite', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probabilité (%)')),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_fermeture_prevue', models.DateField(verbose_name='Date de fermeture prévue')),
                ('date_fermeture_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fermeture réelle')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('commande_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.commande', verbose_name='Commande liée')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devis_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.devis', verbose_name='Devis lié')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.statutopportunite', verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='crm.clientcrm', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='etapepipeline',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.statutopportunite', verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_par_defaut', models.DurationField(blank=True, null=True, verbose_name='Durée par défaut')),
                ('couleur', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Type d'activité",
                'verbose_name_plural': "Types d'activité",
                'unique_together': {('nom', 'entreprise')},
            },
        ),
        migrations.CreateModel(
            name='NoteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_important', models.BooleanField(default=False, verbose_name='Important')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='crm.clientcrm', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Note client',
                'verbose_name_plural': 'Notes client',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_echeance', models.DateTimeField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=10, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('rappel', models.BooleanField(default=False, verbose_name='Rappel')),
                ('date_rappel', models.DateTimeField(blank=True, null=True, verbose_name='Date de rappel')),
                ('resultat', models.TextField(blank=True, verbose_name='Résultat')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('opportunites', models.ManyToManyField(blank=True, related_name='activites', to='crm.opportunite', verbose_name='Opportunités')),
                ('type_activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.typeactivite', verbose_name="Type d'activité")),
                ('clients', models.ManyToManyField(blank=True, related_name='activites', to='crm.clientcrm', verbose_name='Clients')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SourceLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Source de lead',
                'verbose_name_plural': 'Sources de leads',
                'unique_together': {('nom', 'entreprise')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pipelinevente',
            unique_together={('nom', 'entreprise')},
        ),
        migrations.AlterUniqueTogether(
            name='etapepipeline',
            unique_together={('pipeline', 'statut')},
        ),
    ]
