# Generated by Django 5.1.2 on 2025-09-09 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0008_mouvementstock_reference'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunite',
            name='commande_liee',
        ),
        migrations.RemoveField(
            model_name='opportunite',
            name='devis_lie',
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='STOCK.client', verbose_name='Client'),
        ),
    ]
