# Generated by Django 5.1.2 on 2025-09-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_opportunite_commande_liee_and_more'),
        ('ventes', '0022_alter_facture_numero_alter_facture_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='devis_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.devis', verbose_name='Devis lié'),
        ),
    ]
