# Generated by Django 5.1.2 on 2025-09-10 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_opportunite_devis_lie'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('assignation', "Assignation d'opportunité"), ('rappel', 'Rappel de date'), ('changement_statut', 'Changement de statut'), ('activite', 'Activité planifiée'), ('systeme', 'Notification système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lue', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RegleAutomatisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_declencheur', models.CharField(choices=[('creation_opportunite', "Création d'opportunité"), ('changement_statut', 'Changement de statut'), ('assignation', 'Assignation à un commercial'), ('date_approchant', 'Date approchant'), ('activite_terminee', 'Activité terminée')], max_length=50)),
                ('type_action', models.CharField(choices=[('notification', 'Notification'), ('email', 'Email'), ('changement_statut', 'Changer le statut'), ('creation_activite', 'Créer une activité'), ('assignation', 'Assigner à un utilisateur')], max_length=50)),
                ('parametres', models.JSONField(default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
            ],
            options={
                'verbose_name': "Règle d'automatisation",
                'verbose_name_plural': "Règles d'automatisation",
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sujet', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('variables_disponibles', models.TextField(help_text='Liste des variables disponibles séparées par des virgules')),
                ('actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise')),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Templates email',
            },
        ),
    ]
