# Generated by Django 5.1.2 on 2025-08-27 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code journal')),
                ('intitule', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('type_journal', models.CharField(choices=[('achat', 'Achats'), ('vente', 'Ventes'), ('banque', 'Banque'), ('caisse', 'Caisse'), ('divers', 'Divers')], max_length=20, verbose_name='Type de journal')),
                ('actif', models.BooleanField(default=True, verbose_name='Journal actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Journal Comptable',
                'verbose_name_plural': 'Journaux Comptables',
                'ordering': ['code'],
                'unique_together': {('code', 'entreprise')},
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name="Numéro d'écriture")),
                ('date_ecriture', models.DateField(verbose_name="Date d'écriture")),
                ('date_comptable', models.DateField(verbose_name='Date comptable')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('piece_justificative', models.CharField(blank=True, max_length=100, verbose_name='Pièce justificative')),
                ('montant_devise', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant en devise')),
                ('montant_devise_etrangere', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant en devise étrangère')),
                ('code_devise_etrangere', models.CharField(blank=True, max_length=3, verbose_name='Code devise étrangère')),
                ('taux_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Taux de change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journalcomptable', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
                'ordering': ['-date_ecriture', '-numero'],
                'unique_together': {('numero', 'entreprise')},
            },
        ),
        migrations.CreateModel(
            name='PlanComptableOHADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=1, verbose_name='Classe')),
                ('numero', models.CharField(max_length=10, verbose_name='Numéro de compte')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit')], max_length=10, verbose_name='Type de compte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Plan Comptable OHADA',
                'verbose_name_plural': 'Plans Comptables OHADA',
                'ordering': ['numero'],
                'unique_together': {('numero', 'entreprise')},
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrepartie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ligneecriture', verbose_name='Contrepartie')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecriturecomptable', verbose_name='Écriture')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.plancomptableohada', verbose_name='Compte')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['ecriture', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompteAuxiliaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('type_compte', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('autre', 'Autre')], max_length=20, verbose_name='Type de compte')),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise')),
                ('compte_general', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.plancomptableohada', verbose_name='Compte général')),
            ],
            options={
                'verbose_name': 'Compte Auxiliaire',
                'verbose_name_plural': 'Comptes Auxiliaires',
                'ordering': ['code'],
                'unique_together': {('code', 'entreprise')},
            },
        ),
    ]
