# Generated by Django 5.1.2 on 2025-09-03 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('parametres', '0019_entreprise_taux_tva_defaut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='entreprise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='parametres.entreprise', verbose_name='Entreprise'),
            preserve_default=False,
        ),
    ]
