# Generated by Django 5.1.2 on 2025-09-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_ligneecriture_entreprise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteauxiliaire',
            options={'ordering': ['code'], 'verbose_name': 'Compte Auxiliary', 'verbose_name_plural': 'Comptes Auxiliaires'},
        ),
    ]
