# Generated by Django 5.1.2 on 2025-09-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_facturefournisseur'),
        ('comptabilite', '0003_alter_compteauxiliaire_options'),
        ('ventes', '0019_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriturecomptable',
            name='bon_reception_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.bonreception', verbose_name='Bon de réception lié'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='facture_fournisseur_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.facturefournisseur', verbose_name='Facture fournisseur liée'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='paiement_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.paiement', verbose_name='Paiement lié'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='vente_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.ventepos', verbose_name='Vente liée'),
        ),
    ]
