# Generated by Django 5.1.2 on 2025-09-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0002_alter_mouvementstock_options_and_more'),
        ('comptabilite', '0004_ecriturecomptable_bon_reception_lie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriturecomptable',
            name='mouvement_stock_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STOCK.mouvementstock', verbose_name='Mouvement de stock lié'),
        ),
    ]
