# Generated by Django 5.1.2 on 2025-09-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_ecriturecomptable_mouvement_stock_lie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_ecriture',
            field=models.DateTimeField(verbose_name="Date d'écriture"),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='montant_devise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant en devise'),
        ),
    ]
