# Generated by Django 5.1.2 on 2025-09-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_alter_ecriturecomptable_date_ecriture_and_more'),
        ('ventes', '0020_alter_ligneventepos_montant_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriturecomptable',
            name='paiementPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.paiementpos', verbose_name='Paiement lié'),
        ),
    ]
