# Generated by Django 5.1.2 on 2025-09-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_ecriturecomptable_paiementpost'),
        ('ventes', '0020_alter_ligneventepos_montant_tva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='paiementPost',
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='paiement_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.paiementpos', verbose_name='Paiement lié (POS)'),
        ),
    ]
