# Generated by Django 5.1.2 on 2025-09-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0011_alter_commandeachat_options_and_more'),
        ('comptabilite', '0009_ecriturecomptable_paiement_fournisseur_lie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='paiement_fournisseur_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='achats.paiementfournisseur', verbose_name='Paiement fournisseur lié'),
        ),
    ]
