# Generated by Django 5.1.2 on 2025-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_alter_ecriturecomptable_paiement_fournisseur_lie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero',
            field=models.CharField(max_length=500, verbose_name="Numéro d'écriture"),
        ),
    ]
