# Generated by Django 5.1.2 on 2025-09-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_alter_ecriturecomptable_numero'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ecriturecomptable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero',
            field=models.CharField(blank=True, max_length=500, verbose_name="Numéro d'écriture"),
        ),
    ]
