# Generated by Django 5.1.2 on 2025-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0013_alter_ecriturecomptable_unique_together_and_more'),
        ('parametres', '0020_alter_entreprise_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero',
            field=models.CharField(max_length=500, verbose_name="Numéro d'écriture"),
        ),
        migrations.AlterUniqueTogether(
            name='ecriturecomptable',
            unique_together={('numero', 'entreprise', 'journal')},
        ),
    ]
