"""
Django settings for Gstock project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')



try:
    from django.contrib.messages import constants as messages
    MESSAGE_TAGS = {
        messages.DEBUG: 'alert-info',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger'
    }
except Exception as e:
    pass  



LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

#meil automatique

# settings.py
ADMINS = [("Admin", "shadarijerome13@gmail.com")]

DEFAULT_FROM_EMAIL = "shadarijerome13@gmail.com"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shadarijerome13@gmail.com'
EMAIL_HOST_PASSWORD = 'asit teog novq xcep'

# Configuration des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuration des permissions
PERMISSION_DENIED_TEMPLATE = 'erreurs/403.html'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(t(l6uncl9yl+c3!v-=w$+-hra0-th=)qis_i2z(!k!e%q0cmm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['172.20.10.7']
# Config CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Configuration d'authentification
# Authentification
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]



# Sécurité renforcée

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Mettez True en production avec HTTPS
CSRF_COOKIE_SECURE = False     # Mettez True en production avec HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 86400  # 1 jour en secondes


ADMIN_SITE_LOGOUT_REDIRECT_URL = 'security:connexion'

# URLs
LOGIN_URL = 'security:connexion'
LOGIN_REDIRECT_URL = 'security:dashboard_redirect'  # Utilisez la vue de redirection
LOGOUT_REDIRECT_URL = 'security:connexion'

# Configuration des sauvegardes
BACKUP_DIR = os.path.join(BASE_DIR, 'backups')
MAX_BACKUP_FILES = 5  # ou un autre nombre selon la politique de rétention




# Application definition

INSTALLED_APPS = [
    # Utilisez la classe AppConfig
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parametres.apps.ParametresConfig',  # Utilisez la classe AppConfig
    'security.apps.SecurityConfig',   
    'STOCK',
    'achats.apps.AchatsConfig',  
    'ventes.apps.VentesConfig',
    'comptabilite.apps.ComptabiliteConfig',
    'grh',  # Ajoutez cette ligne
    'django_countries',
    'django.contrib.humanize',
    'django_apscheduler',
     'rest_framework',
     'corsheaders',
      'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'django_filters', 
    'django_weasyprint'
  
]
AUTH_USER_MODEL = 'security.UtilisateurPersonnalise'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Doit être placé tôt
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'security.middleware.VerificationAccesMiddleware',  # Après l'authentification
    'security.middleware.JournalisationMiddleware',
    'parametres.middlewares.CurrentEntrepriseMiddleware',
    'parametres.middlewares.EnsureSAASConfigMiddleware',
    'ventes.middleware.PosAccessMiddleware',
    
]

# Autoriser toutes les origines pour le développement (à restreindre en production)
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}
ROOT_URLCONF = 'Gstock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Ajoutez cette ligne
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'STOCK.context_processors.parametre_context',
                'parametres.context_processors.entreprise_info',
            ],
        },
    },
]
WSGI_APPLICATION = 'Gstock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ...existing code...
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Correction ici
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Définir le fuseau horaire (ex: 'Europe/Paris' pour la France)


# settings.py

USE_TZ = True # Crucial pour que Django gère les fuseaux horaires
TIME_ZONE = 'Africa/Lubumbashi' # Ou votre fuseau horaire spécifique, par exemple 'Europe/Paris' ou 'UTC'

# Format d'affichage par défaut des dates
DATETIME_FORMAT = 'd/m/Y H:i'
DATE_FORMAT = 'd/m/Y'
TIME_FORMAT = 'H:i'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static/'),)

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
# Configuration des prévisions
# settings.py
FORECAST_MIN_DATA = 7  # Minimum de points de données
FORECAST_DAYS = 30     # Jours à prévoir
FORECAST_CONFIDENCE = 0.8  # Intervalle de confiance

# Configuration Prophet
PROPHET_CONFIG = {
    'daily_seasonality': True,
    'weekly_seasonality': True,
    'yearly_seasonality': True,
    'changepoint_prior_scale': 0.05,
    'seasonality_mode': 'multiplicative'
}